output_root: '../'
# pytorch_data_dir: '~/workspace/STEGO/datadrive/pytorch-data'
pytorch_data_dir: '/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/datadrive/pytorch-data/'
# experiment_name: "cocostuff"
experiment_name: "cocostuff"
dataset_name: "cocostuff"
# dataset_name: "potsdam"
res: 320
batch_size: 8
num_workers: 24
run_picie: False
run_crf: True
# run_crf: False
run_prediction: True
dark_mode: True
use_ddp: True

model_paths:
  - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/potsdam_exp_cocostuff_extra_layers_date_Feb04_14-43-33/epoch=7-step=798.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/epoch=0-step=16800.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_date_Feb03_12-24-30/epoch=0-step=8500.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_date_Feb02_14-45-36/epoch=0-step=3700.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_date_Feb03_01-00-13/epoch=0-step=9900.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_none_crop_date_Feb03_21-05-56/epoch=0-step=4800.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_date_Feb02_14-45-36/epoch=0-step=3700.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_date_Feb02_01-00-24/epoch=0-step=7300.ckpt"
  # - "/media/ag695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_date_Jan31_14-54-55/epoch=0-step=3000.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_no_zero_clamp_date_Jan30_19-56-49/epoch=0-step=3000.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_no_zero_clamp_date_Jan18_00-18-34/epoch=0-step=7803.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_no_zero_clamp_date_Jan18_21-36-59/epoch=0-step=12603.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_no_zero_clamp_date_Jan18_23-51-43/epoch=0-step=12003.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_no_zero_clamp_date_Jan19_19-50-07/epoch=0-step=13803.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_no_zero_clamp_date_Jan19_22-29-20/epoch=0-step=14703.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_no_zero_clamp_date_Jan16_20-56-26/epoch=0-step=20400.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_no_zero_clamp_date_Jan17_18-28-57/epoch=0-step=31200.ckpt"
  # - "/media/agv/81e50d57-ed58-4bd3-9f3a-d695e6ddfa61/STEGO/checkpoints/cocostuff/cocostuff27_exp_cocostuff_no_zero_clamp_date_Jan17_18-28-57/epoch=0-step=37200.ckpt"
  # - "../saved_models/cocostuff27_vit_base_5.ckpt"
  #- "../saved_models/cityscapes_vit_base_1.ckpt"
  # - "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
